spring.application.name=biblioteca_comenta

#conexiones para la base de datos
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:h2:file:./data/bibliotecadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

spring.h2.console.settings.web-allow-others=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
app.cors.allowed-origins=http://localhost:3000