server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # LA SOLUCIÓN AL 404: 
        # Intenta cargar el archivo ($uri), luego el directorio ($uri/)
        # Si no encuentra ninguno, redirige a /index.html
        try_files $uri $uri/ /index.html;
    }

    # Configuración por defecto para errores de servidor
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}